services:

  ### App (php, nodejs, python) (ports: php-fpm 9000, octane 8000, vite 5173)
  emfy-app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
      args:
        TZ: ${WORKSPACE_TIMEZONE}
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: emfy-app
    hostname: emfy-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    ports:
      - "${APP_VITE_PORT:-5173}:5173"
    depends_on:
      - emfy-mariadb
      - emfy-redis
    environment:
      TZ: ${WORKSPACE_TIMEZONE}
    volumes:
      - ./:/var/www
      - ./docker/app/php_additional.ini:/usr/local/etc/php/conf.d/additional.ini
      - ./docker/app/.zshrc:/home/www-data/.zshrc
      - ./docker/app/bin:/home/www-data/bin
      - ~/.ssh:/home/www-data/.ssh:ro
      - ~/.gitconfig:/home/www-data/.gitconfig
    networks:
      - emfy-network

  ### Nginx (ports: nginx 80)
  emfy-nginx:
    image: nginx:stable-alpine
    container_name: emfy-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "${NGINX_PORT:-80}:80"
    depends_on:
      - emfy-app
    environment:
      TZ: ${WORKSPACE_TIMEZONE}
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/log:/var/log/nginx
    networks:
      - emfy-network

  ### MariaDB (ports: mysql 3306)
  emfy-mariadb:
    image: mariadb:10.11-rc
    container_name: emfy-mariadb
    restart: unless-stopped
    tty: true
    ports:
      - "${MYSQL_PORT}:3306" # Отключен внешний доступ
    environment:
      TZ: ${WORKSPACE_TIMEZONE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - emfy-mariadb-data:/var/lib/mysql
      - ./docker/mariadb/sql:/docker-entrypoint-initdb.d
    networks:
      - emfy-network

  ### Redis (ports: redis 6379)
  emfy-redis:
    image: redis:alpine3.18
    container_name: emfy-redis
    restart: unless-stopped
    environment:
      TZ: ${WORKSPACE_TIMEZONE}
    volumes:
      - emfy-redis-data:/data
      - ./docker/redis/log:/log
    command: ["redis-server"]
    networks:
      - emfy-network

  ### phpMyAdmin (ports: gui 80)
  emfy-phpmyadmin:
    image: phpmyadmin:5.2
    container_name: emfy-phpmyadmin
    restart: unless-stopped
    ports:
      - "${PHPMYADMIN_PORT:-8010}:80"
    environment:
      PMA_HOST: emfy-mariadb
      UPLOAD_LIMIT: 512M
    networks:
      - emfy-network

  ### NGROK (ports: 4040)
  emfy-ngrok:
    image: 'ngrok/ngrok:alpine'
    container_name: emfy-ngrok
    environment:
      # токен тут оставлью так как он безплатный, особо некому не нужен, зато можно сразу запускать и протестить без внешного сервера.
      NGROK_AUTHTOKEN: 2nF9iO86sVLv0L4ChYwipa65RSC_zHbVpD9g2CZAvcwrBrgo
    command: "http --domain=legally-fleet-hen.ngrok-free.app emfy-nginx:80"
    ports:
      - '4040:4040'
    networks:
      - emfy-network
    depends_on:
      - emfy-app

networks:

  emfy-network:
    driver: bridge

volumes:

  emfy-mariadb-data:
    driver: local

  emfy-redis-data:
    driver: local

  emfy-mailpit:
    driver: local